name    'ehazlett-asgard'
version '0.0.2'
source 'https://github.com/ehazlett/puppet-module-asgard/'
author 'ehazlett'
license 'Apache License, Version 2.0'
summary 'Installs Asgard (https://github.com/Netflix/asgard)'
description 'Installs Asgard (https://github.com/Netflix/asgard)'
project_page 'https://github.com/ehazlett/puppet-module-asgard/'
